# Generated by Django 4.2.5 on 2023-09-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('RegisterId', models.AutoField(primary_key=True, serialize=False)),
                ('RegisterDate', models.DateField()),
                ('RegisterBackup', models.BooleanField()),
                ('RegisterObservations', models.TextField(max_length=2548)),
            ],
        ),
    ]
