# Generated by Django 4.2.5 on 2023-09-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0002_alter_register_registerobservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='RegisterDate',
            field=models.DateField(auto_now=True),
        ),
    ]
