# Generated by Django 4.2.5 on 2024-04-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RegisterApp", "0003_alter_register_registerdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecificFunction",
            fields=[
                ("SFId", models.AutoField(primary_key=True, serialize=False)),
                ("SFTitle", models.TextField(max_length=2548)),
                ("SFDescription", models.TextField(max_length=5000, null=True)),
            ],
        ),
    ]
